# Generated by Django 5.2 on 2025-04-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_question_quiz_option_question_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizsubmission',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
